version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5001:8080"
    volumes:
      - ./backend/database.db:/app/database.db
