version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8800:80' #localport:docker port
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '5001:8080' #database port : localport
    env_file:
      - config.env
    volumes:
      - ./backend/database.db:/app/database.db
